---
- name: Create overlay networks
  community.docker.docker_network:
    name: "{{ network.name }}"
    state: "{{ network.state }}"
    scope: "{{ network.scope }}"
    driver: "{{ network.driver }}"
    internal: "{{ network.internal | default(false) }}"
    attachable: "{{ network.attachable | default(false) }}"
    enable_ipv6: "{{ network.attachable | default(false) }}"
    force: "{{ network.attachable | default(false) }}"
  loop: "{{ swarm_overlay_networks_list | flatten }}"
  loop_control:
    loop_var: network
    label:
      - "{{ network }}"
  run_once: true

- name: Deploy stacks
  community.docker.docker_stack:
    name: "{{ stack.name }}"
    compose: "{{ stack.compose }}"
    state: "{{ stack.state }}"
    prune: true
  loop: "{{ swarm_stacks_list | flatten }}"
  loop_control:
    loop_var: stack
    label:
      - "{{ stack.name }}"
      - "{{ stack.state }}"
  run_once: true
