---
- name: Deploy overlay networks
  community.docker.docker_network:
    name: "{{ network.name }}"
    state: "{{ network.state }}"
    scope: "{{ network.scope }}"
    driver: "{{ network.driver }}"
    internal: "{{ network.internal | default(false) }}"
    attachable: "{{ network.attachable | default(false) }}"
    enable_ipv6: "{{ network.attachable | default(false) }}"
    force: "{{ network.attachable | default(false) }}"
    labels: "{{ network.labels | default(omit) }}"
    ipam_config: "{{ network.ipam_config | default(omit) }}"
    ipam_driver: "{{ network.ipam_driver | default(omit) }}"
    ipam_driver_options: "{{ network.ipam_driver_options | default(omit) }}"
    driver_options: "{{ network.driver_options | default(omit) }}"
  loop: "{{ swarm_overlay_networks_list | flatten }}"
  loop_control:
    loop_var: network
    label: "name:{{ network.name }}, state:{{ network.state }}"
  run_once: true

- name: Deploy stacks
  community.docker.docker_stack:
    name: "{{ stack.name }}"
    compose: "{{ stack.compose }}"
    state: "{{ stack.state }}"
    prune: true
    resolve_image: always
  loop: "{{ swarm_stacks_list | flatten }}"
  loop_control:
    loop_var: stack
    label: "name:{{ stack.name }}, state:{{ stack.state }}"
  run_once: true
