---
- name: create overlay networks
  community.docker.docker_network:
    name: "{{ network }}"
    state: present
    scope: swarm
    driver: overlay
  loop: "{{ swarm_overlay_networks_list | flatten }}"
  loop_control:
    loop_var: network
    label:
      - "{{ network }}"
  run_once: true

- name: deploy stacks
  community.docker.docker_stack:
    name: "{{ stack.name }}"
    compose: "{{ stack.compose }}"
    state: "{{ stack.state }}"
    prune: true
  loop: "{{ swarm_stacks_list | flatten }}"
  loop_control:
    loop_var: stack
    label:
      - "{{ stack.name }}"
      - "{{ stack.state }}"
  run_once: true
