---
- name: Install necessary python packages
  tags:
    - install
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
    break_system_packages: True
  with_items:
    - docker
    - jsondiff

- name: Include deploy tasks
  tags:
    - deploy
  when: swarm_stacks_action == "deploy"
  ansible.builtin.include_tasks:
    file: tasks/sub-tasks/stacks_deploy.yml

- name: Include rm tasks
  tags:
    - rm
  when: swarm_stacks_action == "rm"
  ansible.builtin.include_tasks:
    file: tasks/sub-tasks/stacks_rm.yml
