---
- name: Install necessary python packages
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - jsondiff

- name: Include deploy tasks
  ansible.builtin.include_tasks:
    file: tasks/sub-tasks/stacks_deploy.yml
  when: swarm_stacks_action == "deploy"

- name: Include rm tasks
  ansible.builtin.include_tasks:
    file: tasks/sub-tasks/stacks_rm.yml
  when: swarm_stacks_action == "rm"
